[package]
name = "tdbp-ui-druid"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.23.14"

[dependencies.druid]
version = "0.7.0"
features = ["image"]

[dependencies.piet]
version = "0.3.1"
features = ["image", "jpeg"]
